name: Python CI Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-py${{ matrix.python-version }}-pip-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip and wheel
      run: |
        python -m pip install --upgrade pip
        pip install wheel
    - name: Lint with ruff
      uses: chartboost/ruff-action@v1
    - name: Install SAGA
      run: |
        pip install .[full]
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
